BaseUrl= ""
LanguageCode= "en-US"
Title= "Hugo Theme Air"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2016"
canonifyurls = true

[author]
  name = "Jourdan"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "Space Futures Consulting, LLC"
  cover = "images/user.jpg"
  author = "Jourdan"
  authorlocation = ""
  authorwebsite = ""
  bio= "my bio"
  logo = "images/user.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "Jourdan"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  mainSections = ["post"]
